name: Java Release CI

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Generate Documentation
      run: mvn -Pcreate-docs site
    
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "capitalismx-ui/target/capitalismx-ui-*.jar,docs"
        token: ${{ secrets.GITHUB_TOKEN }}
      
